"""
Zepy - CI/CD Pipeline Configuration Generator
Generates GitHub Actions, GitLab CI, and pre-commit hook configurations.
"""

from pathlib import Path
from typing import Optional


def generate_github_actions_yaml(
    target: str = ".",
    fail_on: str = "HIGH",
    sarif_output: Optional[str] = "zepy-results.sarif",
    python_version: str = "3.11",
) -> str:
    sarif_upload = ""
    if sarif_output:
        sarif_upload = f"""
      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: {sarif_output}
"""

    return f"""# ⚡ ZEPY AI Security Scanner — GitHub Actions CI/CD Workflow
# Auto-generated by ZEPY
# https://github.com/4mm47/zepy

name: ZEPY AI & LLM Vulnerability Scan

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  schedule:
    - cron: '0 6 * * 1'   # Weekly Monday 06:00 UTC

permissions:
  contents: read
  security-events: write   # Required for uploading SARIF to GitHub Code Scanning

jobs:
  zepy-security-audit:
    name: ZEPY AI Security Audit
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🐍 Set up Python {python_version}
        uses: actions/setup-python@v5
        with:
          python-version: '{python_version}'
          cache: 'pip'

      - name: 📦 Install ZEPY
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/4mm47/zepy.git

      - name: ⚡ Run ZEPY AI Vulnerability Scan
        run: |
          python -m zepy scan {target} \\
            --sarif {sarif_output} \\
            --json zepy-report.json \\
            --fail-on {fail_on}
{sarif_upload}
      - name: 📊 Upload JSON scan report as artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: zepy-scan-report
          path: |
            zepy-report.json
            {sarif_output}
          retention-days: 30
"""


def generate_gitlab_ci_yaml(
    target: str = ".",
    fail_on: str = "HIGH",
    python_version: str = "3.11",
) -> str:
    return f"""# ⚡ ZEPY AI Security Scanner — GitLab CI/CD Pipeline
# Auto-generated by ZEPY
# https://github.com/4mm47/zepy

stages:
  - security-scan

variables:
  PYTHON_VERSION: "{python_version}"

zepy-ai-security-scan:
  stage: security-scan
  image: python:$PYTHON_VERSION-slim
  before_script:
    - pip install --upgrade pip
    - pip install git+https://github.com/4mm47/zepy.git
  script:
    - python -m zepy scan {target} \\
        --json zepy-report.json \\
        --fail-on {fail_on}
  artifacts:
    when: always
    paths:
      - zepy-report.json
    reports:
      junit: zepy-report.json
    expire_in: 30 days
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
"""


def generate_pre_commit_config() -> str:
    return """# .pre-commit-config.yaml
# Auto-generated by ZEPY
# Run: pre-commit install  then  pre-commit run --all-files

repos:
  - repo: local
    hooks:
      - id: zepy-scan
        name: ZEPY AI & LLM Security Scan
        entry: python -m zepy scan
        language: system
        types: [python]
        args: [--fail-on, CRITICAL]
        pass_filenames: false
"""


def write_ci_file(platform: str, output_dir: str = ".", **kwargs) -> str:
    """
    Generate and write a CI config file.
    Returns the written file path.
    """
    output_path = Path(output_dir)

    if platform == "github":
        workflows_dir = output_path / ".github" / "workflows"
        workflows_dir.mkdir(parents=True, exist_ok=True)
        target_file = workflows_dir / "zepy-security.yml"
        content = generate_github_actions_yaml(**kwargs)
    elif platform == "gitlab":
        target_file = output_path / ".gitlab-ci-zepy.yml"
        content = generate_gitlab_ci_yaml(**kwargs)
    elif platform == "pre-commit":
        target_file = output_path / ".pre-commit-config.yaml"
        content = generate_pre_commit_config()
    else:
        raise ValueError(f"Unsupported platform: {platform!r}. Choose: github, gitlab, pre-commit")

    target_file.write_text(content, encoding="utf-8")
    return str(target_file)
